# Generated by Django 4.0.3 on 2022-04-08 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topup',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balances.balance'),
        ),
        migrations.AddField(
            model_name='payment',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balances.balance'),
        ),
        migrations.AddField(
            model_name='balance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
