# Generated by Django 4.0.3 on 2022-04-08 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='balances.balance'),
        ),
        migrations.AlterField(
            model_name='topup',
            name='balance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='balances.balance'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='balance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='balances.balance'),
        ),
    ]
