# Generated by Django 4.0.3 on 2022-04-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0004_balance_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='remarks',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
